image: gitpod/workspace-full


# when starting a workspace all docker images are ready
tasks:
  - name: docker-up
    command: sudo docker-up
  - name: Set Siga environment variable
    env:
      PROP_SIGA_BASE_URL: $GITPOD_WORKSPACE_URL
  - name: sigadoc-starter
    prebuild: |
      sudo docker-up       
    command: |
      docker-compose up && gp await-port 8080 && gp preview $(gp url 8080)
 
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
